const String longLoremString = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor. Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam. Maecenas fermentum consequat mi. Donec fermentum. Pellentesque malesuada nulla a mi. Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque. Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat.

Cras mollis scelerisque nunc. Nullam arcu. Aliquam consequat. Curabitur augue lorem, dapibus quis, laoreet et, pretium ac, nisi. Aenean magna nisl, mollis quis, molestie eu, feugiat in, orci. In hac habitasse platea dictumst. Fusce convallis, mauris imperdiet gravida bibendum, nisl turpis suscipit mauris, sed placerat dui dolor sit amet urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus. Ut varius tincidunt libero. Phasellus dolor. Maecenas vestibulum mollis diam. Pellentesque ut est.

Praesent tristique eros in metus ullamcorper, non hendrerit orci pulvinar. Sed auctor ac turpis nec placerat. Maecenas id orci nisi. Nullam id dolor at mi luctus feugiat ut in risus. Vestibulum tristique ante non magna faucibus, id bibendum orci dapibus. Quisque pharetra est in arcu interdum condimentum. Mauris vitae augue augue. Fusce vel risus nec erat ultricies ullamcorper. Nulla porttitor erat eu risus viverra, vel sollicitudin sapien tempor. Nulla facilisi. Duis euismod, felis eget congue laoreet, sapien magna sollicitudin lorem, id cursus felis odio a purus. Vestibulum egestas sapien in odio placerat, at pharetra odio tincidunt.

Vestibulum eu odio vel lacus laoreet fermentum. Cras in leo metus. Nullam tristique faucibus nisl ac hendrerit. Donec ornare lectus urna, ut vestibulum purus commodo ut. Nulla a arcu ut arcu elementum viverra. In consequat orci ut erat condimentum, sed malesuada odio bibendum. Nunc auctor id turpis id efficitur. Mauris egestas elit eget lectus pharetra, sed suscipit odio viverra. Curabitur sit amet eros auctor, vehicula turpis in, accumsan risus. Suspendisse potenti. Integer sollicitudin justo ut justo cursus, eget lacinia odio consectetur. Curabitur nec orci eget orci dapibus sollicitudin nec non arcu. Curabitur at nunc et elit fringilla suscipit id eget sem. Integer scelerisque aliquet odio id pharetra. Donec consequat sit amet lacus ac posuere.
''';
